//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("FlZlModel", "FK_FJ_Field_Html", "FJ_BasicHtml", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MoneyRetard.Models.FJ_BasicHtml), "FJ_Field_Html", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoneyRetard.Models.FJ_Field_Html), true)]

#endregion

namespace MoneyRetard.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class FlZlEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“FlZlEntities”部分中的连接字符串初始化新 FlZlEntities 对象。
        /// </summary>
        public FlZlEntities() : base("name=FlZlEntities", "FlZlEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FlZlEntities 对象。
        /// </summary>
        public FlZlEntities(string connectionString) : base(connectionString, "FlZlEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FlZlEntities 对象。
        /// </summary>
        public FlZlEntities(EntityConnection connection) : base(connection, "FlZlEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_AffixUrl> FJ_AffixUrl
        {
            get
            {
                if ((_FJ_AffixUrl == null))
                {
                    _FJ_AffixUrl = base.CreateObjectSet<FJ_AffixUrl>("FJ_AffixUrl");
                }
                return _FJ_AffixUrl;
            }
        }
        private ObjectSet<FJ_AffixUrl> _FJ_AffixUrl;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_BasicData> FJ_BasicData
        {
            get
            {
                if ((_FJ_BasicData == null))
                {
                    _FJ_BasicData = base.CreateObjectSet<FJ_BasicData>("FJ_BasicData");
                }
                return _FJ_BasicData;
            }
        }
        private ObjectSet<FJ_BasicData> _FJ_BasicData;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_BasicField> FJ_BasicField
        {
            get
            {
                if ((_FJ_BasicField == null))
                {
                    _FJ_BasicField = base.CreateObjectSet<FJ_BasicField>("FJ_BasicField");
                }
                return _FJ_BasicField;
            }
        }
        private ObjectSet<FJ_BasicField> _FJ_BasicField;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_BasicHtml> FJ_BasicHtml
        {
            get
            {
                if ((_FJ_BasicHtml == null))
                {
                    _FJ_BasicHtml = base.CreateObjectSet<FJ_BasicHtml>("FJ_BasicHtml");
                }
                return _FJ_BasicHtml;
            }
        }
        private ObjectSet<FJ_BasicHtml> _FJ_BasicHtml;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_Field_Html> FJ_Field_Html
        {
            get
            {
                if ((_FJ_Field_Html == null))
                {
                    _FJ_Field_Html = base.CreateObjectSet<FJ_Field_Html>("FJ_Field_Html");
                }
                return _FJ_Field_Html;
            }
        }
        private ObjectSet<FJ_Field_Html> _FJ_Field_Html;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_File> FJ_File
        {
            get
            {
                if ((_FJ_File == null))
                {
                    _FJ_File = base.CreateObjectSet<FJ_File>("FJ_File");
                }
                return _FJ_File;
            }
        }
        private ObjectSet<FJ_File> _FJ_File;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_Select> FJ_Select
        {
            get
            {
                if ((_FJ_Select == null))
                {
                    _FJ_Select = base.CreateObjectSet<FJ_Select>("FJ_Select");
                }
                return _FJ_Select;
            }
        }
        private ObjectSet<FJ_Select> _FJ_Select;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_User> FJ_User
        {
            get
            {
                if ((_FJ_User == null))
                {
                    _FJ_User = base.CreateObjectSet<FJ_User>("FJ_User");
                }
                return _FJ_User;
            }
        }
        private ObjectSet<FJ_User> _FJ_User;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_UserInfo> FJ_UserInfo
        {
            get
            {
                if ((_FJ_UserInfo == null))
                {
                    _FJ_UserInfo = base.CreateObjectSet<FJ_UserInfo>("FJ_UserInfo");
                }
                return _FJ_UserInfo;
            }
        }
        private ObjectSet<FJ_UserInfo> _FJ_UserInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FJ_ValueType> FJ_ValueType
        {
            get
            {
                if ((_FJ_ValueType == null))
                {
                    _FJ_ValueType = base.CreateObjectSet<FJ_ValueType>("FJ_ValueType");
                }
                return _FJ_ValueType;
            }
        }
        private ObjectSet<FJ_ValueType> _FJ_ValueType;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 FJ_AffixUrl EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_AffixUrl(FJ_AffixUrl fJ_AffixUrl)
        {
            base.AddObject("FJ_AffixUrl", fJ_AffixUrl);
        }
    
        /// <summary>
        /// 用于向 FJ_BasicData EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_BasicData(FJ_BasicData fJ_BasicData)
        {
            base.AddObject("FJ_BasicData", fJ_BasicData);
        }
    
        /// <summary>
        /// 用于向 FJ_BasicField EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_BasicField(FJ_BasicField fJ_BasicField)
        {
            base.AddObject("FJ_BasicField", fJ_BasicField);
        }
    
        /// <summary>
        /// 用于向 FJ_BasicHtml EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_BasicHtml(FJ_BasicHtml fJ_BasicHtml)
        {
            base.AddObject("FJ_BasicHtml", fJ_BasicHtml);
        }
    
        /// <summary>
        /// 用于向 FJ_Field_Html EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_Field_Html(FJ_Field_Html fJ_Field_Html)
        {
            base.AddObject("FJ_Field_Html", fJ_Field_Html);
        }
    
        /// <summary>
        /// 用于向 FJ_File EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_File(FJ_File fJ_File)
        {
            base.AddObject("FJ_File", fJ_File);
        }
    
        /// <summary>
        /// 用于向 FJ_Select EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_Select(FJ_Select fJ_Select)
        {
            base.AddObject("FJ_Select", fJ_Select);
        }
    
        /// <summary>
        /// 用于向 FJ_User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_User(FJ_User fJ_User)
        {
            base.AddObject("FJ_User", fJ_User);
        }
    
        /// <summary>
        /// 用于向 FJ_UserInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_UserInfo(FJ_UserInfo fJ_UserInfo)
        {
            base.AddObject("FJ_UserInfo", fJ_UserInfo);
        }
    
        /// <summary>
        /// 用于向 FJ_ValueType EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFJ_ValueType(FJ_ValueType fJ_ValueType)
        {
            base.AddObject("FJ_ValueType", fJ_ValueType);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_AffixUrl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_AffixUrl : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_AffixUrl 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_AffixUrl CreateFJ_AffixUrl(global::System.Int32 id)
        {
            FJ_AffixUrl fJ_AffixUrl = new FJ_AffixUrl();
            fJ_AffixUrl.id = id;
            return fJ_AffixUrl;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String guid
        {
            get
            {
                return _guid;
            }
            set
            {
                OnguidChanging(value);
                ReportPropertyChanging("guid");
                _guid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("guid");
                OnguidChanged();
            }
        }
        private global::System.String _guid;
        partial void OnguidChanging(global::System.String value);
        partial void OnguidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_BasicData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_BasicData : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_BasicData 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_BasicData CreateFJ_BasicData(global::System.Int32 id)
        {
            FJ_BasicData fJ_BasicData = new FJ_BasicData();
            fJ_BasicData.id = id;
            return fJ_BasicData;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bid
        {
            get
            {
                return _bid;
            }
            set
            {
                OnbidChanging(value);
                ReportPropertyChanging("bid");
                _bid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bid");
                OnbidChanged();
            }
        }
        private Nullable<global::System.Int32> _bid;
        partial void OnbidChanging(Nullable<global::System.Int32> value);
        partial void OnbidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bhid
        {
            get
            {
                return _bhid;
            }
            set
            {
                OnbhidChanging(value);
                ReportPropertyChanging("bhid");
                _bhid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bhid");
                OnbhidChanged();
            }
        }
        private Nullable<global::System.Int32> _bhid;
        partial void OnbhidChanging(Nullable<global::System.Int32> value);
        partial void OnbhidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String guid
        {
            get
            {
                return _guid;
            }
            set
            {
                OnguidChanging(value);
                ReportPropertyChanging("guid");
                _guid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("guid");
                OnguidChanged();
            }
        }
        private global::System.String _guid;
        partial void OnguidChanging(global::System.String value);
        partial void OnguidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_BasicField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_BasicField : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_BasicField 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_BasicField CreateFJ_BasicField(global::System.Int32 id)
        {
            FJ_BasicField fJ_BasicField = new FJ_BasicField();
            fJ_BasicField.id = id;
            return fJ_BasicField;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FieldType
        {
            get
            {
                return _FieldType;
            }
            set
            {
                OnFieldTypeChanging(value);
                ReportPropertyChanging("FieldType");
                _FieldType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FieldType");
                OnFieldTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _FieldType;
        partial void OnFieldTypeChanging(Nullable<global::System.Int32> value);
        partial void OnFieldTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PID
        {
            get
            {
                return _PID;
            }
            set
            {
                OnPIDChanging(value);
                ReportPropertyChanging("PID");
                _PID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PID");
                OnPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PID;
        partial void OnPIDChanging(Nullable<global::System.Int32> value);
        partial void OnPIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_BasicHtml")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_BasicHtml : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_BasicHtml 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_BasicHtml CreateFJ_BasicHtml(global::System.Int32 id)
        {
            FJ_BasicHtml fJ_BasicHtml = new FJ_BasicHtml();
            fJ_BasicHtml.id = id;
            return fJ_BasicHtml;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createTime
        {
            get
            {
                return _createTime;
            }
            set
            {
                OncreateTimeChanging(value);
                ReportPropertyChanging("createTime");
                _createTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createTime");
                OncreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createTime;
        partial void OncreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsStart
        {
            get
            {
                return _IsStart;
            }
            set
            {
                OnIsStartChanging(value);
                ReportPropertyChanging("IsStart");
                _IsStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsStart");
                OnIsStartChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsStart;
        partial void OnIsStartChanging(Nullable<global::System.Boolean> value);
        partial void OnIsStartChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlZlModel", "FK_FJ_Field_Html", "FJ_Field_Html")]
        public EntityCollection<FJ_Field_Html> FJ_Field_Html
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FJ_Field_Html>("FlZlModel.FK_FJ_Field_Html", "FJ_Field_Html");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FJ_Field_Html>("FlZlModel.FK_FJ_Field_Html", "FJ_Field_Html", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_Field_Html")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_Field_Html : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_Field_Html 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_Field_Html CreateFJ_Field_Html(global::System.Int32 id)
        {
            FJ_Field_Html fJ_Field_Html = new FJ_Field_Html();
            fJ_Field_Html.id = id;
            return fJ_Field_Html;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bfid
        {
            get
            {
                return _bfid;
            }
            set
            {
                OnbfidChanging(value);
                ReportPropertyChanging("bfid");
                _bfid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bfid");
                OnbfidChanged();
            }
        }
        private Nullable<global::System.Int32> _bfid;
        partial void OnbfidChanging(Nullable<global::System.Int32> value);
        partial void OnbfidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bhid
        {
            get
            {
                return _Bhid;
            }
            set
            {
                OnBhidChanging(value);
                ReportPropertyChanging("Bhid");
                _Bhid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bhid");
                OnBhidChanged();
            }
        }
        private Nullable<global::System.Int32> _Bhid;
        partial void OnBhidChanging(Nullable<global::System.Int32> value);
        partial void OnBhidChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlZlModel", "FK_FJ_Field_Html", "FJ_BasicHtml")]
        public FJ_BasicHtml FJ_BasicHtml
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FJ_BasicHtml>("FlZlModel.FK_FJ_Field_Html", "FJ_BasicHtml").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FJ_BasicHtml>("FlZlModel.FK_FJ_Field_Html", "FJ_BasicHtml").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FJ_BasicHtml> FJ_BasicHtmlReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FJ_BasicHtml>("FlZlModel.FK_FJ_Field_Html", "FJ_BasicHtml");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FJ_BasicHtml>("FlZlModel.FK_FJ_Field_Html", "FJ_BasicHtml", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_File")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_File : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_File 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_File CreateFJ_File(global::System.Int32 id)
        {
            FJ_File fJ_File = new FJ_File();
            fJ_File.id = id;
            return fJ_File;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createTime
        {
            get
            {
                return _createTime;
            }
            set
            {
                OncreateTimeChanging(value);
                ReportPropertyChanging("createTime");
                _createTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createTime");
                OncreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createTime;
        partial void OncreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_Select")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_Select : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_Select 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_Select CreateFJ_Select(global::System.Int32 id)
        {
            FJ_Select fJ_Select = new FJ_Select();
            fJ_Select.id = id;
            return fJ_Select;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private Nullable<global::System.Int32> _type;
        partial void OntypeChanging(Nullable<global::System.Int32> value);
        partial void OntypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_User 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_User CreateFJ_User(global::System.Int32 id)
        {
            FJ_User fJ_User = new FJ_User();
            fJ_User.id = id;
            return fJ_User;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pwd
        {
            get
            {
                return _Pwd;
            }
            set
            {
                OnPwdChanging(value);
                ReportPropertyChanging("Pwd");
                _Pwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pwd");
                OnPwdChanged();
            }
        }
        private global::System.String _Pwd;
        partial void OnPwdChanging(global::System.String value);
        partial void OnPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAllocation
        {
            get
            {
                return _IsAllocation;
            }
            set
            {
                OnIsAllocationChanging(value);
                ReportPropertyChanging("IsAllocation");
                _IsAllocation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAllocation");
                OnIsAllocationChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAllocation;
        partial void OnIsAllocationChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAllocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAgency
        {
            get
            {
                return _IsAgency;
            }
            set
            {
                OnIsAgencyChanging(value);
                ReportPropertyChanging("IsAgency");
                _IsAgency = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAgency");
                OnIsAgencyChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAgency;
        partial void OnIsAgencyChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAgencyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Limits
        {
            get
            {
                return _Limits;
            }
            set
            {
                OnLimitsChanging(value);
                ReportPropertyChanging("Limits");
                _Limits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Limits");
                OnLimitsChanged();
            }
        }
        private Nullable<global::System.Int32> _Limits;
        partial void OnLimitsChanging(Nullable<global::System.Int32> value);
        partial void OnLimitsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_UserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_UserInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_UserInfo 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_UserInfo CreateFJ_UserInfo(global::System.Int32 id)
        {
            FJ_UserInfo fJ_UserInfo = new FJ_UserInfo();
            fJ_UserInfo.id = id;
            return fJ_UserInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserType
        {
            get
            {
                return _UserType;
            }
            set
            {
                OnUserTypeChanging(value);
                ReportPropertyChanging("UserType");
                _UserType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserType");
                OnUserTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _UserType;
        partial void OnUserTypeChanging(Nullable<global::System.Int32> value);
        partial void OnUserTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserRealName
        {
            get
            {
                return _UserRealName;
            }
            set
            {
                OnUserRealNameChanging(value);
                ReportPropertyChanging("UserRealName");
                _UserRealName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserRealName");
                OnUserRealNameChanged();
            }
        }
        private global::System.String _UserRealName;
        partial void OnUserRealNameChanging(global::System.String value);
        partial void OnUserRealNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Icard_1
        {
            get
            {
                return _Icard_1;
            }
            set
            {
                OnIcard_1Changing(value);
                ReportPropertyChanging("Icard_1");
                _Icard_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Icard_1");
                OnIcard_1Changed();
            }
        }
        private Nullable<global::System.Int32> _Icard_1;
        partial void OnIcard_1Changing(Nullable<global::System.Int32> value);
        partial void OnIcard_1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Icard_1_Num
        {
            get
            {
                return _Icard_1_Num;
            }
            set
            {
                OnIcard_1_NumChanging(value);
                ReportPropertyChanging("Icard_1_Num");
                _Icard_1_Num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Icard_1_Num");
                OnIcard_1_NumChanged();
            }
        }
        private global::System.String _Icard_1_Num;
        partial void OnIcard_1_NumChanging(global::System.String value);
        partial void OnIcard_1_NumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Icard_2
        {
            get
            {
                return _Icard_2;
            }
            set
            {
                OnIcard_2Changing(value);
                ReportPropertyChanging("Icard_2");
                _Icard_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Icard_2");
                OnIcard_2Changed();
            }
        }
        private Nullable<global::System.Int32> _Icard_2;
        partial void OnIcard_2Changing(Nullable<global::System.Int32> value);
        partial void OnIcard_2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Icard_2_Num
        {
            get
            {
                return _Icard_2_Num;
            }
            set
            {
                OnIcard_2_NumChanging(value);
                ReportPropertyChanging("Icard_2_Num");
                _Icard_2_Num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Icard_2_Num");
                OnIcard_2_NumChanged();
            }
        }
        private global::System.String _Icard_2_Num;
        partial void OnIcard_2_NumChanging(global::System.String value);
        partial void OnIcard_2_NumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MustNum
        {
            get
            {
                return _MustNum;
            }
            set
            {
                OnMustNumChanging(value);
                ReportPropertyChanging("MustNum");
                _MustNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MustNum");
                OnMustNumChanged();
            }
        }
        private global::System.String _MustNum;
        partial void OnMustNumChanging(global::System.String value);
        partial void OnMustNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private Nullable<global::System.Int32> _Area;
        partial void OnAreaChanging(Nullable<global::System.Int32> value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LegalPeo
        {
            get
            {
                return _LegalPeo;
            }
            set
            {
                OnLegalPeoChanging(value);
                ReportPropertyChanging("LegalPeo");
                _LegalPeo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LegalPeo");
                OnLegalPeoChanged();
            }
        }
        private global::System.String _LegalPeo;
        partial void OnLegalPeoChanging(global::System.String value);
        partial void OnLegalPeoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QQ
        {
            get
            {
                return _QQ;
            }
            set
            {
                OnQQChanging(value);
                ReportPropertyChanging("QQ");
                _QQ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QQ");
                OnQQChanged();
            }
        }
        private global::System.String _QQ;
        partial void OnQQChanging(global::System.String value);
        partial void OnQQChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAgency
        {
            get
            {
                return _IsAgency;
            }
            set
            {
                OnIsAgencyChanging(value);
                ReportPropertyChanging("IsAgency");
                _IsAgency = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAgency");
                OnIsAgencyChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAgency;
        partial void OnIsAgencyChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAgencyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlZlModel", Name="FJ_ValueType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FJ_ValueType : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FJ_ValueType 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static FJ_ValueType CreateFJ_ValueType(global::System.Int32 id)
        {
            FJ_ValueType fJ_ValueType = new FJ_ValueType();
            fJ_ValueType.id = id;
            return fJ_ValueType;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }

    #endregion

    
}
